### ISSUE TITLE
Not able to parse files encoded with something different than utf-8

### ISSUE THREAD

**Issue by Herve07h22** [themodernjavascript/react-papaparse#4]
The encoding setting options in configOptions are not propagated to the FileReader.

I suggest to write 
`reader.readAsText(e.target.files[0], configOptions.encoding || "utf-8")`
instead of 
`reader.readAsText(e.target.files[0])`

**Comment by Bunlong** [comment]
@Herve07h22 Thank for your suggestion we will fix it soon. Thanks!

**Comment by Bunlong** [comment]
@Herve07h22 react-papaparse v2.0 has been released. The bug was fixed. Thanks!

**Comment by Bunlong** [comment]
@Herve07h22 Could I close the issue?

**Comment by Herve07h22** [comment]
Sure :)

**Comment by Bunlong** [comment]
@Herve07h22 Thank you so much! :)
